### PR TITLE
fix: polyfill function

### LINKED ISSUE #96: document is undefined
It looks like 1.2.0v doesnt support server side rendering. We should wrap this with condition.

Zrzut ekranu 2020-09-13 o 17 15 55

### PR DESCRIPTION
**Pull request by magic-akari**
- check if supportsScrollBehavior before polyfill
- lazy eval supportsScrollBehavior
- move all original function to common file
- fix window.scrollBy
- fix #96

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { windowScrollByPolyfill } from "./Window.scrollBy.js";
 import { windowScrollToPolyfill } from "./Window.scrollTo.js";
 
 export const polyfill = (options?: IAnimationOptions) => {
-    if (supportsScrollBehavior) {
+    if (supportsScrollBehavior()) {
         return;
     }
```
Comment (bartdominiak) [inline src/index.ts:14]: I tried to build this PR, but I'm getting a lot of errors:
seamless-build-procces

I fixed that by adding:

```js
"moduleResolution": "node",
"types": ["@types/node"]
```

inside `compilerOptions` object in `tsconfig.json` file

PS: I've very fundamental experience of typescript, so maybe I miss something.

File: src/Window.scrollTo.ts [hunk 2]
```diff
@@ -1,19 +1,14 @@
...
 
 export { windowScroll as windowScrollTo } from "./Window.scroll.js";
 
-let $original: (x: number, y: number) => void;
-
-export const getOriginalFunc = () => {
-    if ($original === undefined) {
-        $original = (window.scrollTo || window.scroll).bind(window);
+export const windowScrollToPolyfill = (options?: IAnimationOptions) => {
+    if (supportsScrollBehavior()) {
```
Comment (bartdominiak) [inline src/Window.scrollTo.ts]: I think this variable should be more descriptive, something like `isScrollBehaviorSupported` - which `is` prefix telling us that we are expecting a bool type.

File: src/Window.scrollBy.ts [hunk 3]
```diff
@@ -1,32 +1,30 @@
...
-        return $original;
-    })();
+    if (supportsScrollBehavior()) {
+        return;
+    }
 
     window.scrollBy = function scrollBy() {
         const [arg0 = 0, arg1 = 0] = arguments;
 
         if (typeof arg0 === "number" && typeof arg1 === "number") {
```
Comment (bartdominiak) [inline src/Window.scrollBy.ts]: There is uneeded call with default `0` argument, and also `arg0`, `arg1` variables should be more descriptive.

Maybe we can change it, to something like this:

```js
const [xAxis, yAxis] = arguments;
const isValidAxis = axis => typeof axis === "number" && axis > 0;

if (isValidAxis(xAxis) && isValidAxis(yAxis)) {
  return windowScrollBy({ left: xAxis, top: yAxis });
}

Comment (bartdominiak) [reply src/Window.scrollBy.ts]: There is one more thing `window.scrollBy` accepts Numbers and also Number of Strings (like `'123'`). I'd would be great to support both. Maybe it's a good challange to use typescript here, and valid both types?

File: src/Element.scroll.ts [hunk 4]
```diff
@@ -1,22 +1,16 @@
...
-    return $original;
-};
+import {
+    IAnimationOptions,
+    IContext,
+    IScrollToOptions,
+    modifyPrototypes,
+    now,
+    original,
+    step,
```
Comment (bartdominiak) [inline src/Element.scroll.ts:11]: I'd like to change `step`, `original`, `now` to more descriptive variable names. It's hard to understand from my persperctive what exaclly do this part of functions, without digging inside the `common.js` 😿

File: src/index.ts (hunk 1 above)
Comment (magic-akari) [reply src/index.ts:14]: `yarn link` may be helpful.

File: src/Window.scrollBy.ts (hunk 3 above)
Comment (magic-akari) [reply src/Window.scrollBy.ts]: Thanks a lot! You found the bug.
We should to make sure that the polyfill function behaves as same as the standard native function at runtime.

File: src/Element.scroll.ts (hunk 4 above)
Comment (magic-akari) [reply src/Element.scroll.ts:11]: The variable naming is the hardest part :(
I feel a headache when I want to name it. And these functions are only for internal use. So I kept it as it was.

**Review by bartdominiak — APPROVED** [review]
